# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

  # Python dependencies
  - package-ecosystem: "pip"
    directory: "./data_pipeline"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Frontend
  - package-ecosystem: "npm"
    directory: "./frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Backend
  - package-ecosystem: "npm"
    directory: "./backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
