services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_BACKEND_URL: "/api"  # Why do I need to add an arg here?
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=/api

  database:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -q"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - db_data:/var/lib/postgresql/data

  data_pipeline:
    build:
      context: ./data_pipeline
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://$${POSTGRES_USER}:$${POSTGRES_PASSWORD}@database:5432/$${POSTGRES_DB}

volumes:
  db_data: