services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - prod.env
    ports:
      - "3000:3000"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - backend

  data_pipeline:
    build:
      context: ./data_pipeline
      dockerfile: Dockerfile
    profiles:
      - data_pipeline
    depends_on:
      - database

  database:
    image: postgres:17
    env_file:
      - prod.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
