services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - prod.env
    ports:
      - "3000:3000"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    environment:
      - VITE_BACKEND_URL=http://localhost:3000

  data_pipeline:
    build:
      context: ./data_pipeline
      dockerfile: Dockerfile
    profiles:
      - data_pipeline
    depends_on:
      - database

  database:
    image: postgres:17
    env_file:
      - prod.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
