services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    environment:
      - VITE_BACKEND_URL=http://localhost:3000

  data_pipeline:
    build:
      context: ./data_pipeline
      dockerfile: Dockerfile
    depends_on:
      - database

  database:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  author_ingestion:
    build: ./data_pipeline
    working_dir: /app
    command: >
      python -m core.extract_researcher_links
      --model gpt-4o-mini
      --temperature 0.0
      --max_completion_tokens 75
      --max_results 5
      --limit 100
    env_file:
      - .env
    depends_on:
      - database
    restart: "no"

  paper_ingestion:
    tty: true
    stdin_open: true
    build: ./data_pipeline
    working_dir: /app
    volumes:
      - arxiv_data:/app/data
    command: >
      python -m core.pipeline 
      --author_tracking_period_months 24
      --author_num_papers_enter_threshold 20
      --author_num_papers_keep_threshold 20
      --paper_tracking_period_months 6
      --temperature 0.0
      --max_completion_tokens 40
      --limit 9000
      --sample_freq 100
      --new_topic_threshold 20
    env_file:
      - .env
    depends_on:
      - database
    restart: "no"

volumes:
  db_data:
  arxiv_data:
