services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - prod.env
    ports:
      - "3000:3000"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_BACKEND_URL: "/api"  # Why do I need to add an arg here?
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=/api

  database:
    image: postgres:17
    env_file:
      - prod.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    external:
      name: cs-topics-explorer_db_data
